#!/bin/bash

# =======================
# -------- alias --------
# =======================

alias ..="cd .."
alias l="ls -h"
alias la="ls -ahl"
alias ll="ls -hl"
alias ls="ls --color=auto"

alias cp="cp -i"
alias lns="ln -s"
alias mv="mv -i"
alias rm="rm -i"

alias diff="diff --color=auto"
alias grep='grep --color=auto'

alias df="df -h"
alias du="du -h -d 1"
alias free="free -ht"

# https://stackoverflow.com/a/9074343
alias glg1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias glg2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias glg3="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)%n%n%w(84,2,4)%C(white)%B%C(reset)%n' --all"
alias glg="glg1"
