#!/bin/bash

# ============================
# -------- completion --------
# ============================

# bash completion
if ! shopt -oq posix; then
    if [[ -f /usr/share/bash-completion/bash_completion ]]; then
        source /usr/share/bash-completion/bash_completion
    elif [[ -f /etc/bash_completion ]]; then
        source /etc/bash_completion
    fi
fi

# pip completion
function _pip_completion()
{
    COMPREPLY=( $( COMP_WORDS=${COMP_WORDS[*]} \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 2>/dev/null ) )
}
complete -o default -F _pip_completion pip3
