#!/bin/bash

# ========================
# -------- config --------
# ========================

# umask
export DOTFILES_UMASK_DEFAULT=027
umask $DOTFILES_UMASK_DEFAULT

# prompt
setPrompt

# npm
setNpmPrefix "$HOME/.npm_global"

# shell option
HISTCONTROL=ignoreboth
HISTFILESIZE=4096
HISTSIZE=1024

shopt -s checkwinsize
shopt -s histappend

# colored GCC warnings and errors
export GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
