#!/bin/bash

# ========================
# -------- config --------
# ========================

# prompt
export PROMPT_COMMAND=promptCommandFunction
export PS1=$( parsePrompt "<<1;32>>[\u@\h]<<0>>:<<1;34>>\w<<0>>\\$ " $( isColorTerminal ) )

# shell option
HISTCONTROL=ignoreboth
HISTFILESIZE=4096
HISTSIZE=1024

shopt -s checkwinsize
shopt -s histappend

# general option
umask 027

# colored GCC warnings and errors
export GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"
