#!/bin/bash

# ==========================
# -------- function --------
# ==========================

function exportPath()
{
    local i
    for i in "$@"; do
        [[ $PATH =~ $i ]] || PATH=$i:$PATH
    done
    export PATH
}

function setNpmPrefix()
{
    if command -v npm > /dev/null; then
        [[ ! -f $HOME/.npmrc ]] && npm config set prefix "$1"
        exportPath "$1/bin"
    fi
}
