#!/usr/bin/env bash

# ==========================
# -------- function --------
# ==========================

function exportPath()
{
    local i
    for i in "$@"; do
        [[ $PATH =~ $i ]] || PATH=$i:$PATH
    done
    export PATH
}
