#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return ;;
esac

# ======================
# -------- main --------
# ======================

function main()
{
    local -r SCRIPT_ROOT=$( dirname "$( realpath "${BASH_SOURCE[0]}" )" )

    export DOTFILES_ROOT=$( dirname "$SCRIPT_ROOT" )

    source "$SCRIPT_ROOT/script/completion"
    source "$SCRIPT_ROOT/script/function"
    source "$SCRIPT_ROOT/script/prompt"
    source "$SCRIPT_ROOT/script/config"
    source "$SCRIPT_ROOT/script/alias"
}

main
unset main
